#!/usr/bin/env python3


include: "rules/common.smk"
include: "rules/samtools_import.smk"
include: "rules/samtools_fasta.smk"


# this is from the bpa_dataportal_downloads project
data_file_dict = {
    "616629_FISH_BRF_m84118_250714_235739_s3.hifi_reads.bc2071.bam": "https://data.bioplatforms.com/dataset/bpa-fish-pacbio-hifi-616629-m84118_250714_235739_s3/resource/f816c011c7d82bc4c2c58cb93be5761b/download/616629_FISH_BRF_m84118_250714_235739_s3.hifi_reads.bc2071.bam",
}

rule format_config_file:
    input:
        sanger_config_template=local(sanger_config_template),
    output:
        rendered_yaml=add_bucket_to_path(
            Path(
                dataset_id, "results", "config", "sangertol_genomeassembly_params.yaml"
            )
        ),
    params:
        pacbio_reads=[rules.samtools_fasta.output.reads],
        hic_reads=[rules.samtools_import.output.cram],
    container:
        get_container("ncbi-datasets-pylib")
    script:
        "scripts/format_config_file.py"


rule config_target:
    default_target: True
    localrule: True
    input:
        storage.s3(rules.samtools_import.output),
        storage.s3(rules.samtools_fasta.output),
        rendered_yaml=storage.s3(rules.format_config_file.output.rendered_yaml),
    output:
        "results/sangertol_genomeassembly_params.yaml",
    shell:
        "cp {input.rendered_yaml} {output}"


#module test_rm:
#    snakefile:
#        github("tomharrop/test-module-rm", path="workflow/Snakefile", tag="v0.0.6")
#    config:
#        {
#            **config,
#            "query_genome": storage.s3(
#                "s3://pawsey1132.amy.testing/XanthorrhoeaJohnsonii376315/results/sanger_tol/XanthorrhoeaJohnsonii376315.v1/scaffolding_hap1/"
#                    "yahs/out.break.yahs/hap1_scaffolds_final.fa",
#            ),
#        }


#use rule * from test_rm as test_rm_*

#use rule clean from test_rm as test_rm_clean with:
#    resources:
#        runtime=lambda wildcards, attempt: 720 * attempt,
#        mem_mb=lambda wildcards, attempt: 48e3 * attempt,

#use rule all from test_rm as rm_all with:
#    output:
#        storage.s3(
#                "s3://pawsey1132.amy.testing/XanthorrhoeaJohnsonii376315/results/out_scaffolds_final.masked.fa.gz",
#            )