---
executor: cluster-generic
cluster-generic-submit-cmd:
  mkdir -p logs/{rule} &&
  sbatch
  --time={resources.time}
  {resources.partitionFlag}
  --cpus-per-task={threads}
  --mem={resources.mem_mb}
  --job-name=smk-{rule}
  --output=logs/{rule}/{rule}-%j.out
  --parsable
  # --gres={resources.gres}         # enable for GPU
cluster-generic-status-cmd: status-sacct-robust.sh
cluster-generic-cancel-cmd: scancel
default-resources:
  - partitionFlag=""
  - mem_mb=4000
  - time=5
  - proj=punim1712
  # - gres=' '         # enable for GPU
restart-times: 0
max-jobs-per-second: 50
max-status-checks-per-second: 10
local-cores: 2
cores: 50
latency-wait: 60
jobs: 128
keep-going: true
keep-storage-local-copies: true
rerun-incomplete: true
printshellcmds: true
use-apptainer: true
use-conda: False
apptainer-args: "-B $PWD,$TMPDIR,/data \
  --nv \
  -H $(mktemp -d) \
  --pwd $PWD \
  --containall --cleanenv --writable-tmpfs"
